version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  Consumer:
    container_name: consumer
    image: consumer:latest
    build:
      context: Consumer
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - services-network
    depends_on:
      RabbitMQ:
        condition: service_healthy

  Producer:
    container_name: producer
    image: producer:latest
    build:
      context: Producer
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - services-network
    depends_on:
      RabbitMQ:
        condition: service_healthy

  RabbitMQ:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
    - services-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
    - services-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "mytopic"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - services-network

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - services-network

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana   
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./configs/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus    
    networks:
      - services-network