version: '3.8'
networks:
  services-network:
    driver: bridge 

services:
  producer:
    container_name: producer
    image: producer:latest
    build:
      context: producer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - services-network
  
  consumer:
    container_name: consumer
    image: consumer:latest
    build:
      context: consumer
      dockerfile: Dockerfile  
    ports:
      - "8082:8082"
    networks:
      - services-network