version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"     
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks: 
      - logging-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.0
    build: filebeat
    container_name: filebeat
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200    
    labels:
      co.elastic.logs/enabled: "false"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
    networks:
      - logging-network
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
      - "SERVER_NAME=localhost"
      - "XPACK_MONITORING_ENABLED=false"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - logging-network

  producer:
    build:
      context: ./Producer
      dockerfile: Dockerfile
    container_name: Producer
    ports:
      - "8081:8081"
    networks:
      - logging-network
    
  consumer:
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    container_name: Consumer
    ports:
      - "8082:8082"
    networks:
      - logging-network

networks: 
  logging-network:
    driver: bridge
