Vagrant.configure("2") do | config |
    config.vm.define "bookservice" do |bookservice|
        bookservice.vm.box = "Ubuntu-Vagrant"
        bookservice.vm.hostname = "books"
        bookservice.vm.network "private_network", ip: "192.168.99.100"
	bookservice.vm.network "forwarded_port", guest: 80, host: 8000
        bookservice.vm.network "forwarded_port", guest: 5050, host: 5050        
        bookservice.vm.provision "shell", path: "docker-setup.sh"
        bookservice.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
	bookservice.vm.provision :docker
        bookservice.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
        end
    end    
end
